# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateTimeField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
