# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieBox', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='MovieActor', to='MovieBox.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='UserMovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Comedy'), (2, 'Action'), (3, 'Thriller'), (4, 'Drama'), (5, 'Horror'), (6, 'Romance'), (7, 'Fantasy'), (8, 'Sci-Fi')]),
        ),
    ]
