# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0004_auto_20180105_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.CharField(max_length=200)),
                ('favourites', models.ManyToManyField(related_name='Favourites', to='MovieBox.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieBox.MBUser')),
            ],
        ),
    ]
