# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0005_mbuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.CharField(default='actor-defaul.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
    ]
