# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0006_auto_20180106_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='Movies', to='MovieBox.Actor'),
        ),
    ]
