# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0007_auto_20180113_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='UserMovie', to='MovieBox.MBUser'),
        ),
    ]
