# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0014_auto_20180113_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbuserprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbuserprofile',
            name='favourites',
            field=models.ManyToManyField(related_name='Favourites', to='MovieBox.Movie'),
        ),
        migrations.AlterField(
            model_name='mbuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mbuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MBUserProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
