# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0015_auto_20180113_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mbuserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
