# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0016_auto_20180113_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to=b''),
        ),
    ]
