# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0017_auto_20180113_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to=b''),
        ),
    ]
